"""Generate script/Seed.s.sol from data/seed_cards.json (real slabs + appraisals)."""
import json
d = json.load(open("data/seed_cards.json"))
conf = {"NARRATIVE": 1, "MODEST": 2, "REAL": 3}
risk = {"REJECT": 1, "C": 2, "B": 3, "A": 4}
def s(x): return x.replace('"', "'")
lines = []
for c in d["cards"]:
    a = c["appraisal"]
    lines.append(f'''        registry.publish("{c['grader']}", "{c['certId']}", {a['fmvLow']}, {a['fmvPoint']}, {a['fmvHigh']}, {a['ltvBps']}, {a['confidenceScore']*10}, {a['keptCount']}, AppraisalRegistry.Confidence({conf[a['confidenceTier']]}), AppraisalRegistry.Risk({risk[a['riskTier']]}), {str(a['eligible']).lower()});
        cards.mint(holder, "{c['grader']}", "{c['certId']}", "{s(c['grade'])}", "{s(c['name'])}");''')
body = "\n".join(lines)
open("script/Seed.s.sol", "w").write(f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// AUTO-GENERATED by data/gen_seed_script.py from data/seed_cards.json. Do not edit by hand.
// Source: {d['source']} | pulled {d['pulledAt']}
// Price basis: {d['priceBasis']}

import {{Script, console2}} from "forge-std/Script.sol";
import {{AppraisalRegistry}} from "../src/AppraisalRegistry.sol";
import {{GradedCard}} from "../src/GradedCard.sol";

/// Publishes price certificates for {len(d['cards'])} real vaulted slabs and mints demo card tokens.
///   forge script script/Seed.s.sol --rpc-url robinhood_testnet --broadcast
contract Seed is Script {{
    function run() external {{
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address holder = vm.envOr("CARD_HOLDER", vm.addr(pk));
        string memory dep = vm.readFile(string.concat("deployments/", vm.toString(block.chainid), ".json"));
        AppraisalRegistry registry = AppraisalRegistry(vm.parseJsonAddress(dep, ".registry"));
        GradedCard cards = GradedCard(vm.parseJsonAddress(dep, ".cards"));

        vm.startBroadcast(pk);
{body}
        vm.stopBroadcast();
        console2.log("seeded cards:", uint256({len(d['cards'])}));
    }}
}}
''')
print("wrote script/Seed.s.sol")
