// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// AUTO-GENERATED by data/gen_seed_script.py from data/seed_cards.json. Do not edit by hand.
// Source: Collector Crypt public marketplace API (api.collectorcrypt.com/marketplace) | pulled 2026-09-23T06:26:29+00:00
// Price basis: insured valuations + live asking prices of other vaulted slabs of the same item and grade; NOT completed sales

import {Script, console2} from "forge-std/Script.sol";
import {AppraisalRegistry} from "../src/AppraisalRegistry.sol";
import {GradedCard} from "../src/GradedCard.sol";

/// Publishes price certificates for 6 real vaulted slabs and mints demo card tokens.
///   forge script script/Seed.s.sol --rpc-url robinhood_testnet --broadcast
contract Seed is Script {
    function run() external {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        address holder = vm.envOr("CARD_HOLDER", vm.addr(pk));
        string memory dep = vm.readFile(string.concat("deployments/", vm.toString(block.chainid), ".json"));
        AppraisalRegistry registry = AppraisalRegistry(vm.parseJsonAddress(dep, ".registry"));
        GradedCard cards = GradedCard(vm.parseJsonAddress(dep, ".cards"));

        vm.startBroadcast(pk);
        registry.publish("PSA", "109308847", 272513, 290000, 307487, 5000, 920, 15, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "109308847", "GEM-MT 10", "2021 #218 Full Art/Rayquaza Vmax PSA 10 Sword & Shield Evolving Skies");
        registry.publish("PSA", "118973623", 287520, 320000, 352480, 5000, 870, 15, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "118973623", "GEM-MT 10", "2019 #SM168 Full Art/Pikachu & Zekrom GX PSA 10 SM Black Star Promo");
        registry.publish("PSA", "100863346", 126858, 133100, 139342, 5000, 940, 12, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "100863346", "GEM-MT 10", "2022 #186 Full Art/Lugia V PSA 10 Sword & Shield Silver Tempest");
        registry.publish("PSA", "154790134", 55002, 58000, 60998, 5000, 940, 19, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "154790134", "GEM-MT 10", "2023 #GG69 Full Art/Giratina Vstar PSA 10 Sword and Shield Crown Zenith");
        registry.publish("PSA", "153708045", 37502, 39500, 41498, 5000, 940, 23, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "153708045", "GEM-MT 10", "2022 #TG20 Full Art/Rayquaza Vmax PSA 10 Sword & Shield Silver Tempest");
        registry.publish("PSA", "111992917", 26253, 27250, 28247, 5000, 960, 14, AppraisalRegistry.Confidence(3), AppraisalRegistry.Risk(4), true);
        cards.mint(holder, "PSA", "111992917", "GEM-MT 10", "2022 #TG23 Full Art/Umbreon Vmax PSA 10 Sword & Shield Brilliant Stars");
        vm.stopBroadcast();
        console2.log("seeded cards:", uint256(6));
    }
}
